apiVersion: v1
kind: ConfigMap
metadata:
  name: db-config
data:
  # Add your database environment variables here
  MYSQL_ROOT_PASSWORD: "rootpassword"  # Change this as per your .env file or secure practice

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: wp-config
data:
  # Add your WordPress environment variables here
  WORDPRESS_DB_HOST: "mariadb"
  WORDPRESS_DB_USER: "root"
  WORDPRESS_DB_PASSWORD: "rootpassword"  # Ensure this matches the MYSQL_ROOT_PASSWORD in db-config
